### ISSUE TITLE
React Native 0.64.X android builds will fail with current build command

### ISSUE THREAD

**Issue by kieran-osgood** [react-native-community/react-native-circleci-orb#100]
### Orb version

v5.1.0

### What happened

I've been trying to fix some issues with my app running with the orb, I'd opened an issue here which describes it fully, believing it to be related to the tool I used to initialise the app: https://github.com/infinitered/ignite/issues/1676 , but it seems that since react-native 0.64 there has been a bump to the minSdkVersion, see lines 392:

https://github.com/facebook/react-native/blob/0.63-stable/ReactAndroid/build.gradle
https://github.com/facebook/react-native/blob/0.64-stable/ReactAndroid/build.gradle

As a result this causes the `assembleAndroidTest` to fail, meaning the build fails and can't run detox tests as no APK produced.

Now I'm not exactly certain on the entire process the orb has, so forgive me if this is a naive approach, I was wondering if:
1. adjusting the command to target just `app:assembleAndroidTest`
2. adding the option to remove it from the `build` job 
3. move it to the test job
would be suitable?

I was thinking I'd add a PR for an additional string, or enum parameter [`assembleAndroidTest`,`app:assembleAndroidTest`, ``] (figure this guides people to either be all the tests, just app, or none, but string would be more flexible)- that allows users to adjust the command for react-native 0.64+ users whilst package maintainers increase their minSdkVersion?

**Comment by matt-oakes** [comment]
Close and fixed in [v5.2.0](https://github.com/react-native-community/react-native-circleci-orb/releases/tag/v5.2.0)
