### ISSUE TITLE
get it to work with fastlane

### ISSUE THREAD

**Issue by forge-phap-dinh** [react-native-community/react-native-circleci-orb#115]
### Orb version
5.6.0

### What happened

trying to deploy to fastlane gives this error

#!/bin/bash -eo pipefail
bundle exec fastlane android debug
/bin/bash: bundle: command not found

Exited with code exit status 127
CircleCI received exit code 127

### Expected behavior

React native app should deploy to fastlane

**Comment by cortinico** [comment]
> /bin/bash: bundle: command not found

Is failing since you running on a runner where ruby is missing or not installed correctly.
Have you checked if ruby is available in your runner?

**Comment by forge-phap-dinh** [comment]
@cortinico from our understanding the runner should have been configured by the orb to have ruby installed. if the runner is not configured with ruby in the orb, what is the recommended way to setup a runner with this orb?

**Comment by cortinico** [comment]
> what is the recommended way to setup a runner with this orb?

Have you seen this documentation page? https://circleci.com/developer/orbs/orb/react-native-community/react-native
Specifically what's the `executor` you're specifying for your fastlane job? 
I'm not entirely sure, but I believe both `rn/linux_js` and `rn/macos` should work.

**Comment by forge-phap-dinh** [comment]
i switched over to rn/linux_android and installed ruby on there to get around this issue. thanks
