### ISSUE TITLE
Can't replace existing directory with non-directory tar

### ISSUE THREAD

**Issue by forge-phap-dinh** [react-native-community/react-native-circleci-orb#117]
### Orb version
5.6.0

### What happened
using this yaml code
- rn/ios_build:
          build_configuration: Release
          device: iPhone X
          name: build_ios_release
          project_path: ios/Example.xcodeproj
          requires:
            - analyse_js
          scheme: Example

I get this error

Found a cache from build 287 at brew-cache-arch1-darwin-amd64-6_58-4

Size: 988 MiB
Cached paths:
  * /usr/local/Homebrew
  * /Users/distiller/Library/Caches/Homebrew

Downloading cache archive...
Unarchiving cache...

Failed to unarchive cache

Error untarring cache: Error extracting tarball /var/folders/6y/gy9gggt14379c_k39vwb50lc0000gn/T/cache2953294140 : usr/local/Homebrew/Library/Homebrew/shims/scm: Can't replace existing directory with non-directory tar: Error exit delayed from previous errors. : exit status 1

### Expected behavior
A build for ios should be created

**Comment by lukebrandonfarrell** [comment]
Same error on my side for now I'll just be disabling `homebrew_cache`

**Comment by lukebrandonfarrell** [comment]
Upon further inspection I think this has to do with case sensitivity on newer versions of MacOS. @forge-phap-dinh what is your xCode version specified as in your `config.yml` ? i.e. 

```
 macos:
      xcode: '12.4.0'
```

**Comment by forge-phap-dinh** [comment]
@lukebrandonfarrell thank you for your help. i didn't specify a macos version because the example https://circleci.com/developer/orbs/orb/react-native-community/react-native didn't show I needed to specify one
