### ISSUE TITLE
Usage with CodePush

### ISSUE THREAD

**Issue by gunnartorfis** [react-native-community/react-native-circleci-orb#137]
## What would you like to be added
This is more of a question, I need help figuring out how the optimal workflow would be in our case. 

We're using RN with AppCenter's CodePush and therefore we rarely update the native part of iOS/Android. We'd still want to be able to run E2E tests (using Detox) automatically in our pipes but it feels redundant to build the native apps if there isn't any change. 

The only solution I could figure out would be to detect before running the build part if there is a diff in the `ios` or `android` folder. If there is, build and test like normally. But if there isn't, we could get the bundle somehow (this is the part I'm not sure with) and install it to the simulator/emulator. On mount we'd receive the latest CodePush version and start the E2E tests. 

What other possible workflows can you guys think of? If none, any ideas how we could install the app in the simulators?

**Comment by vonovak** [comment]
hello, thanks for asking.

> The only solution I could figure out would be to detect before running the build part if there is a diff in the ios or android folder

this likely won't catch all the changes you're interested in: eg. when you update a dependency that includes native code, that code lives in `node_modules/xyz/ios(android)`. Maybe the safest way is to invert the change detection: if the only changes on a branch are in your `src` folder where your javascript code lives, then consider the branch as one where you don't need to build the native code.

> we could get the bundle somehow (this is the part I'm not sure with) and install it to the simulator/emulator. On mount we'd receive the latest CodePush version and start the E2E tests.

You could probably publish the changes to a specific codepush deployment (that means you'd have per-branch deployments and so you'd have many of them) and download the update upon app start up.

Alternatively, what can be done is this: build the javascript bundle using `npx react-native bundle`. If you're using hermes you'll also need to transform that using `hermesc` (see [here](https://github.com/facebook/react-native/blob/7cece342336fdbb40b45505965d8d0ddfcbd81fe/scripts/react-native-xcode.sh#L179)).

Then on android, you'd take an old apk, unzip it, replace the bundle with the new one, and create a new apk with the new application bundle.
On iOS, I'm not sure how that would be done but on simulator I think it ought to be doable.

Another thing you can look at are the functions [here](https://github.com/facebook/react-native/blob/main/ReactAndroid/src/main/java/com/facebook/react/ReactNativeHost.java) (android) / [sourceURLForBridge](https://github.com/facebook/react-native/blob/main/React/Base/RCTBridgeDelegate.h) (ios) functions that control where to load the app bundle from.

Hope this helps!
