### ISSUE TITLE
Incorrect and inconsistent Ruby versions between executors

### ISSUE THREAD

**Issue by thomsocialbrothers** [react-native-community/react-native-circleci-orb#160]
### Orb version
7.1.1

### What happened
Incorrect and inconsistent Ruby versions between executors

### Expected behavior
To implement the ruby version that is specified by the latest React Native release (0.70), which is version 2.7.5.

Currently, the executor linux_android has Ruby version 2.7.0 installed while the macos executor has Ruby version 2.7.4 installed. Whenever i try to build my application, my Gemfile's ruby version is never met, since the two jobs have different requirements of ruby versions. Besides, none of them includes 2.7.5, which is required by React Native's latest release.

As far as i can see there is no way of selecting a Ruby version through the executor's argument.

**Comment by fotos** [comment]
Closing the issue as stale.
