### ISSUE TITLE
Make "Configure Detox Environment" macOS step optional

### ISSUE THREAD

**Issue by kevindice** [react-native-community/react-native-circleci-orb#167]
## What would you like to be added

I would like to make the "Configure Detox Environment" step optional within the `setup_macos_executor` task - enabled by default but possible to skip.

My use case is that I want to check Podfile.lock integrity on PRs but do not want to do relatively expensive end-to-end testing on PRs.  So, I use the same macos executor and would like otherwise the same setup but without spending over a minute to download and install Detox when I am not using it here.

## Why is this needed

For using the macOS executor for purposes other than Detox.

**Comment by devnev** [comment]
I opened a PR that includes this a while ago, #135

**Comment by kevindice** [comment]
Ah cool, thanks.

**Comment by fotos** [comment]
@devnev @kevindice this has been [released as part of `v7.2.0`](https://github.com/react-native-community/react-native-circleci-orb/releases/tag/v7.2.0). 🎉
