### ISSUE TITLE
Jetify

### ISSUE THREAD

**Issue by markhalonen** [react-native-community/react-native-circleci-orb#20]
My project uses Jetify https://www.npmjs.com/package/jetifier which is an npm tool that transforms some Java files as far as I can tell. So I just need to run this command before doing the `gradlew` build. I confirmed with CircleCI ssh that this is what's causing my build to fail.

How would you recommend I go about doing this currently? I've been trying to use the `persist_to_workspace` in a previous job to no avail, but I can try again tomorrow..

Perhaps I should clone this repo and try to modify it to do the `jetify`? 

Any thoughts appreciated, I'm a beginner at CircleCI orbs, jobs, steps, workflows etc.

**Comment by shauns** [comment]
I believe that if you add `"postinstall": "yarn jetify"` to your package.json (or however your project runs it), it'll kick in after dependencies are installed.

**Comment by markhalonen** [comment]
that worked! thank you sir
