### ISSUE TITLE
adding frozen-lockfile?

### ISSUE THREAD

**Issue by compojoom** [react-native-community/react-native-circleci-orb#28]
# Feature Request
I think that we should install yarn dependencies with --frozen-lockfile:
https://circleci.com/docs/2.0/yarn/
https://stackoverflow.com/questions/52630404/how-to-install-packages-based-on-the-lock-file-with-yarn
https://yarnpkg.com/lang/en/docs/cli/install/

```
If you need reproducible dependencies, which is usually the case with the continuous integration systems, you should pass --frozen-lockfile flag.
```

Any objections?

**Comment by matt-oakes** [comment]
Good idea. Releasing as a breaking change.
