### ISSUE TITLE
android_build command fails

### ISSUE THREAD

**Issue by stwiname** [react-native-community/react-native-circleci-orb#4]
# Bug

`downloadDependencies` task not found when running `android_build` command

```

FAILURE: Build failed with an exception.

* What went wrong:
Task 'downloadDependencies' not found in root project 'XXXX'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 8s
Exited with code 1
```
## Environment info

React native info output:

```bash
React Native Environment Info:
    System:
      OS: macOS 10.14.5
      CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
      Memory: 1.26 GB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
      Yarn: 1.17.3 - ~/.nvm/versions/node/v10.16.0/bin/yarn
      npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
      Android SDK:
        API Levels: 23, 24, 25, 26, 27, 28, 29
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 24.0.1, 25.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.3, 28.0.2, 28.0.3, 29.0.0, 29.0.1
        System Images: android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.4 AI-183.6156.11.34.5692245
      Xcode: 10.3/10G8 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.3 => 16.9.0
      react-native: 0.59.4 => 0.59.4
    npmGlobalPackages:
      react-native-cli: 2.0.1
```
## Steps To Reproduce

On a fresh react-native project

1. `android/gradlew downloadDependencies -p android` will not find the task to download dependencies

This is the same as the step [here](https://github.com/react-native-community/react-native-circleci-orb/blob/master/src/commands/android_build.yml#L46)

Describe what you expected to happen:

1. I guess because this task doesn't exist that it shouldn't be called. Ideally there's another task or some way to add the task to the project

**Comment by only1chi** [comment]
I have the exact problem. Has anyone solved it?

**Comment by stwiname** [comment]
@only1chi, I ended up copying the function from https://github.com/react-native-community/react-native-netinfo/blob/master/example/android/build.gradle#L28

**Comment by cmejet** [comment]
@stwiname thank you for that link! That helped me get past that hurdle. Now to figure out the detox/annotation issue

**Comment by compojoom** [comment]
I also needed that! Thanks for sharing. @matt-oakes maybe this should be really in the docs as in the PR https://github.com/react-native-community/react-native-circleci-orb/commit/a3b3f4eddf780639fc30270fe271c5f9293d42eb
