### ISSUE TITLE
Add support for private NPM repositories - by setting auth token  

### ISSUE THREAD

**Issue by kroeberk** [react-native-community/react-native-circleci-orb#49]
## What would you like to be added

Sadly the default yarn install commands don't support private npm repositories. I had to copy all the tasks and prepend with

  - run:
          name: Prepare private repo access
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc

It would be cool if that cam out of the box. Or at least some way to implement that.

## Why is this needed

Should be self explanatory :)

**Comment by matt-oakes** [comment]
:wave: I presume you are trying to use the jobs. You have two options:

You can, using the currently, release version create you own job made up of the commands you need from this Orb. This is why they are available both as commands and as pre-made jobs. The jobs are meant to account for 90% of people with no or little configuration. The commands are there be to be used if you need something custom. This seems to fit your use-case.

Alternatively, we could add a new parameter, in the same vein as `on_after_initialize`, to run commands *before* yarn install. Maybe `on_before_initialize`?

I think that either of these options would work for you. If you prefer the second option then please open a pull request with the new parameter for me to review.

Let me know if I've misunderstood your issue.
