### ISSUE TITLE
Undocumented dependency

### ISSUE THREAD

**Issue by Masadow** [react-native-community/react-native-circleci-orb#55]
### Orb version

4.2.0

### What happened

Task 'downloadDependencies' not found in root project

### Expected behavior

It should build

From what I found out, you rely on this plugin but the documentation does not state it anywhere: https://github.com/tehlers/gradle-download-dependencies-plugin

**Comment by matt-oakes** [comment]
This is documented in the README: https://github.com/react-native-community/react-native-circleci-orb/blob/master/README.md#android

**Comment by Masadow** [comment]
Oh right, should probably be on https://circleci.com/orbs/registry/orb/react-native-community/react-native ?
