### ISSUE TITLE
Cannot start simulator on version 4.2.0

### ISSUE THREAD

**Issue by MateusAndrade** [react-native-community/react-native-circleci-orb#56]
### Orb version
4.2.0

### What happened
Whenever I run a command that requires the simulator start on iOS, I got the following error:

```shell
#!/bin/bash --login -eo pipefail
xcrun simctl list | awk -F “[()]” ‘{ for (i=2; i<NF; i+=2) print $i }’ | grep ‘^[-A-Z0–9]*$’ | xargs -I uuid xcrun simctl delete uuid
/bin/bash: -c: line 0: syntax error near unexpected token `('

Exited with code exit status 2
```

Possibly related to 2d614fa

![Screen Shot 2020-04-22 at 09 53 42](https://user-images.githubusercontent.com/15278828/79984182-326def80-847f-11ea-84ed-619180119bf1.png)

### Expected behavior
My build should run without any problem

**Comment by matt-oakes** [comment]
Sorry. This was fixed, but Github and CircleCI were down yesterday so the fix never got release. I've just re-run the job now. It should come out as 4.2.1 in a few minutes.

**Comment by MateusAndrade** [comment]
Thanks, I'm testing 4.2.1 here.

**Comment by matt-oakes** [comment]
Thanks. I've reverted the changes from 4.2.0 as they're clearly not working in the CircleCI environment. 4.2.2 should be working as before.
