### ISSUE TITLE
Job fails at Downloading Gradle Dependencies 

### ISSUE THREAD

**Issue by Rhadammanthis** [react-native-community/react-native-circleci-orb#69]
### Orb version
react-native-community/react-native@4.4.2

### What happened

Job fails at Downloading Gradle Dependencies using the default configuration in the example provided

![image](https://user-images.githubusercontent.com/1177492/86119373-a279a100-bad2-11ea-8453-7e553505bf0e.png)

### Expected behavior

The job should compile successfully

**Comment by m2mathew** [comment]
I am getting a similar problem in my project. I think my situation has to do with how my project has implemented security for Android builds. Perhaps you have a similar issue where the `app/build.gradle` has some set up security that looks for keystore values.

**Comment by Rafatcb** [comment]
Try using `git update-index --chmod=+x gradlew` and then commiting/pushing
